version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns:
          - '*'
    commit-message:
      prefix: ci

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      cargo:
        patterns:
          - '*'
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: gomod
    directory: /crates/tailnet/testcontrol
    schedule:
      interval: weekly
      day: monday
    groups:
      gomod:
        patterns:
          - '*'
    commit-message:
      prefix: build
      include: scope
