[package]
name = "e2e"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dev-dependencies]
base64.workspace = true
chacha20poly1305 = { workspace = true, features = ["alloc"] }
collie-core = { path = "../collie-core" }
collie-tls.workspace = true
collied = { path = "../collied" }
futures-util.workspace = true
protocol.workspace = true
serde_json.workspace = true
sha2.workspace = true
tailnet.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite.workspace = true
zeroize.workspace = true

[lints]
workspace = true
